name: node test reusable workflow

on:
    workflow_call:
        inputs:
            project_name:
                required: true
            stage:
                required: true
            ssm_region:
                value: "us-east-1"
        secrets:
            npm_token:
                required: true
            aws_access_key_id:
                required: true
            aws_secret_access_key:
                required: true

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version-file: ".nvmrc"
                  cache: "yarn"
